# HLint configuration file
# https://github.com/ndmitchell/hlint

# Disable use of built-in primitives in Monad module
- ignore: {name: "Use <$>", within: [Monad.liftA, Monad.liftM, Monad.ap]}
- ignore: {name: "Use >=>", within: [Monad]}

# Disable syntax sugar
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use tuple-section", within: [Monad]}

# Specify additional command line arguments
- arguments: [--color]

# Control which extensions can be used
- extensions:
  # all extension are banned by default
  - default: false
  # only these listed extensions can be used
  - name: [FlexibleInstances, FlexibleContexts, TupleSections]

# Add custom hints for this project

# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# Turn on hints that are off by default

# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}

# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}

# Ignore some builtin hints
# - ignore: {name: Use let}
# # Only within certain modules
# - ignore: {name: Use const, within: SpecialModule}

# Define some custom infix operators
# - fixity: infixr 3 ~^#^~
