# HLint configuration file, see https://github.com/ndmitchell/hlint.

# Disable use of built-in primitives in Monad module
- ignore: {name: "Use <$>", within: [Monad]}
- ignore: {name: "Use >=>", within: [Monad]}

# Disable syntax sugar
- ignore: {name: "Use lambda-case"}
- ignore: {name: "Use tuple-section"}

# Disable other rules
- ignore: {name: "Use newtype instead of data"}

# Control which extensions can be used
- extensions:
  # all extension are banned by default
  - default: false
  # only these listed extensions can be used
  - name: []
