name: fp-haskell
version: 0.1.0.0
github: "hubbards/fp-haskell"
license: MIT
author: "Spencer Hubbard"
copyright: "2018 Spencer Hubbard"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on Github at <https://github.com/hubbards/fp-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
  - Arrow
  - Monad
  - Monoid
  - Parser
  - Queue
  - Reader
  - RedBlack
  - RedBlackGADT
  - Register
  - Set
  - Stack
  - State
  - Tree
  - Writer
  dependencies:
  - transformers >= 0.5
  - pretty

tests:
  tests:
    main: Main.hs
    source-dirs: test
    dependencies:
    - fp-haskell
    - filepath
    - doctest >= 0.8
    - HUnit
