name: fp-haskell
version: 0.1.0.0
github: "hubbards/fp-haskell"
license: MIT
author: "Spencer Hubbard"
copyright: "2018 Spencer Hubbard"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/hubbards/fp-haskell#readme>

dependencies:
- base >= 4.7 && < 5

#ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
  - Monad
  - Monoid
  - Password
  - Reader
  - Register
  - Stack
  - State
  - Tree
  - Writer
  dependencies:
  - mtl
  - transformers
  - pretty

tests:
  tests:
    main: Main.hs
    source-dirs: test
    dependencies:
    - fp-haskell
    - HUnit
